{% set name = "tinycss" %}
{% set version = "0.4" %}
{% set sha256 = "12306fb50e5e9e7eaeef84b802ed877488ba80e35c672867f548c0924a76716e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1003
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - tinycss

about:
  home: http://tinycss.readthedocs.io/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Tinycss is a complete yet simple CSS parser for Python.'
  license_family: BSD

extra:
  recipe-maintainers:
    - johanneskoester
    - ccordoba12
