travis:
  secure:
    BINSTAR_TOKEN: hlUadSF3rxqbWxxVXUEq0CsuLhv6tz74HRQ66J/R1/uj7l9IROjIOAyEjAxfBXmwsHLeUbbWXF3IfX0itEHZXMVy2+6zN6dqMe7R6zYe5FCqulomyLMqJc9IH57M0sWS6oaTkeswUZnue68jreE3LZDtS/M8cPQzuI5yV7vRxiOHW1inTKqmSwjqgr8W4PuzYCLj/YoX8EWCByVPJXw8EPRtwu5spY+czRudSiQyXW99HsGQfcqjROphwnAnbL6UmErtzV/xiK1Fo+EwVjlqojV6ny6COAWhLFjPjztlCMHz55dOfZkWuwWrTFEyO/0/r4b8YtBTkvBT1Exe/CYzJd+buVPqRzegKhWA+IVstaTuTOoc3MOjEzm9TxUaWs76eJDw3y+wSbFTP9VwShNzfelNrWykNxuFMk0V1mj9/9Az5Yr4VJPUZbKISLKnzjQ+U1zHMmSX+JB6hjrPbqBnGmBr8/Z3p80gTXzoIyNn7brRg9aqzsD/4DGvZ+n5k1Yr6lS4BXX6tg6l0hMnNmNkw+S/epwxV7/rlKeOP+TGRABRT5S11QJ83D3gemnadGsjuCWPlUDSIYCsM1xxBLWd4DcxohZii0F2dwJOpikzY7gL3yDzlJr+wkvcdnmXyEBljKhu6beeoCZ2C/zrinPDIPi6IZoWXrp1Efimx2iMZ9w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
